### PR TITLE
Added QC commends on CDOM to yaml

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
@callumrollo let me know if this ok and if so I will do it for the other missions

**Comment by callumrollo** [comment]
The yaml is good. I'd prefer a more descriptive comment than "strong temporal decrease" though. Maybe "An unexplained issue with the sensor causes an apparent temporal increase in CDOM."

**Comment by MOchiara** [comment]
@callumrollo what do you think of this?

**Review by callumrollo — APPROVED** [review]

**Comment by callumrollo** [comment]
Looks good!

**Pull request merged**
