### PR TITLE
Aleks patch 2

### PR DESCRIPTION
**Pull request by akmazur**
Hi, I added some deployments yamls.
I was not sure which parameters we should delete from ADCP as there is an issue with time and I think Callum only added pressure and altitude. I copied all of them at the moment but when we decide I will remove unnecessary ones. It's only on 45, 56, 63 and 66 gliders

### CODE REVIEW

**Comment by akmazur** [comment]
Hi, I added some deployments yamls. 
I was not sure which parameters we should delete from ADCP as there is an issue with time and I think Callum only added pressure and altitude. I copied all of them at the moment but when we decide I will remove unnecessary ones. It's only on 45, 56, 63 and 66 gliders.

**Comment by callumrollo** [comment]
Wooh, monster commit! I'll try and look through the yaml this afternoon. First, could you move all the yaml you've edited from draft_yaml to mission_yaml? The automated tests only run on files in mission_yaml

**Comment by callumrollo** [comment]
Wooh green lights!

I'll have a check over the yaml now

**Comment by callumrollo** [comment]
I haven't found any typos in the serial numbers of calibration dates. One potential issue is the formatting of AD2CP beam variables. These are currently:

```
  ad2cp_beam1_cell_number[1]:
    source:       AD2CP_V1_CN[1]
    long_name:    glider beam 1 measure from AD2CP in cell [1]
    standard_name: platform_beam1_measure_ad2cp_cell[1]
    units:        m s-1
    coordinates:  time depth latitude longitude
```

While this is consistent with the way Alseamar have formatted them in the pld1 files, this use of square brackets can mess up downstream processing. I would propose using underscores like we do for OCR. We should also state that this is along beam velocity. So this would be:

```
  ad2cp_vel_beam_1_cell_1:
    source:       AD2CP_V1_CN[1]
    long_name:    glider beam 1 velocity from AD2CP in cell 1
    standard_name: platform_beam1_vel_ad2cp_cell_1
    units:        m s-1
    coordinates:  time depth latitude longitude
```

Note that the source line needs to remain as -is. This is how the target data are identified in Alseamar files.

**Comment by akmazur** [comment]
Suggested changes are made, both in yamls and in the variable file

**Comment by callumrollo** [comment]
There's a lot going on in this one. Is it necessary to keep and review the files in drafts? From what I can tell, these are just outdated versions of the ones in mission_yaml. If so, the old version in drafts should be deleted, so we don't have multiple copies of each file

**Pull request closed without merging**
