### PR TITLE
Updated qc comments on SEA076 M8 and M9

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
@callumrollo sorry I though I changed branch for SEA077_M17 and the SEA076 ones

**Comment by MOchiara** [comment]
@callumrollo no wait I did change branch. Not sure why shows 077 here

**Comment by callumrollo** [comment]
No worries, just got to remember to checkout master before making a new branch. Try doing that and making a PR with just the SEA76 changes.

**Comment by MOchiara** [comment]
@callumrollo I did checkout so not sure why it showed up...

**Pull request closed without merging**
