### PR TITLE
Added yaml for SEA79_M9

### PR DESCRIPTION
**Pull request by MOchiara**

### CODE REVIEW

**Comment by MOchiara** [comment]
@callumrollo

**Comment by callumrollo** [comment]
what did you use as the base for this? Note that we don't use start and end dates anymore. You might need to update your github fork and do a pull

**Review by callumrollo — CHANGES_REQUESTED** [review]
Other than that looks good! Just remove the deployment start and end date lines

**Comment by MOchiara** [comment]
@callumrollo Should be removed now '

**Review by callumrollo — APPROVED** [review]

**Pull request merged**
